name: 'Spinnaker Plugin Metadata Sync'
description: 'Syncs metadata with a Spinnaker plugin metadata repository'
inputs:
  metadata:
    description: ''
    required: true
    default: ''
  binaryUrl:
    description: ''
    required: true
    default: ''
  metadataRepoUrl:
    description: ''
    required: true
    default: ''
  oauthToken:
    description: ''
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--metadata'
  - ${{ inputs.metadata }}
  - '--binary-url'
  - ${{ inputs.binaryUrl }}
  - '--metadata-repo-url'
  - ${{ inputs.metadataRepoUrl }}
  - '--oauth-token'
  - ${{ inputs.oauthToken }}
